server_url: https://vpn.k8s.scg.skku.ac.kr
listen_addr: 0.0.0.0:8080
db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite

ip_prefixes: ["100.64.0.0/10"]

noise:
    private_key_path: /var/lib/headscale/noise_private.key

dns:
    magic_dns: true
    base_domain: scg.internal
    nameservers:
        global: ["1.1.1.1"]
    override_local_dns: true

derp:
    server:
        enabled: true
        region_id: 999
        region_code: "scg-internal"
        region_name: "SCG Internal Access VPN"
        listen_addr: 0.0.0.0:8080
