server_url: https://vpn.k8s.scg.skku.ac.kr
listen_addr: 0.0.0.0:8080

unix_socket: /var/lib/headscale/headscale.sock

noise:
    private_key_path: /var/lib/headscale/noise_private.key

prefixes:
    v4: 100.64.0.0/10
    v6: fd7a:115c:a1e0::/48
    allocation: sequential

database:
    type: sqlite3
    sqlite:
        path: /var/lib/headscale/db.sqlite
        write_ahead_log: true

dns:
    magic_dns: true
    base_domain: scg.internal
    nameservers:
        global:
            - 1.1.1.1
    override_local_dns: true

derp:
    server:
        enabled: true
        region_id: 999
        region_code: "scg-internal"
        region_name: "SCG Internal Access VPN"
        private_key_path: /var/lib/headscale/derp_server_private.key
        stun_listen_addr: "0.0.0.0:3478"
        automatically_add_embedded_derp_region: true
    paths: []
    auto_update_enabled: true
    update_frequency: 24h
