server_url: https://vpn.k8s.scg.skku.ac.kr
listen_addr: 0.0.0.0:8080
db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite
derp:
    server:
        enabled: true
        region_id: 999
        region_code: "scg-internal"
        region_name: "SCG Internal Access VPN"
        listen_addr: 0.0.0.0:8080
dns_config:
    magic_dns: true
    nameservers:
        - 1.1.1.1
