apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: headscale-ingress
    annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-clusterissuer"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
spec:
    tls:
        - hosts:
              - vpn.k8s.scg.skku.ac.kr
          secretName: headscale-tls-secret
    rules:
        - host: vpn.k8s.scg.skku.ac.kr
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: headscale
                            port:
                                number: 8080
