apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - headscale-pvc.yaml
    - headscale-deploy.yaml
    - headscale-svc.yaml
    - ingress.yaml
    - router-deploy.yaml
    - secret.yaml

configMapGenerator:
    - name: headscale-config
      files:
          - config.yaml
